apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  template:
    spec:
      containers:
        - name: container
          env:
            - name: CONTAINERPRO_VARIABLE
              value: "I am container prod."
